### PR TITLE
Updated with last fixes and additions from 20tab master

### PR DESCRIPTION
**Pull request by HaBe2305**
I hope I've caught all your changes. My tests were all successful at least.

### CODE REVIEW

**Comment by getnamo** [comment]
Compiles and runs correctly from a clean slate? (site packages deleted -> re-downloading dependencies)

**Comment by HaBe2305** [comment]
Just testet again, this time with an empty Blueprint project, first copying your latest tensorflow-ue plugin folder into it, then overwriting all files in UEP with my fork files, extract your TF-Examples release and start the project. The Basic example runs like it should. So I guess everything went well enough.

**Comment by getnamo** [comment]
Sounds good, merging.

**Comment by getnamo** [comment]
Made a small mistake with this merge. In my fork, this function https://github.com/getnamo/UnrealEnginePython/blob/5bb20bf1b650606ccac7e6dd9ff2abfe8e299763/Source/UnrealEnginePython/Private/UEPyEngine.cpp#L724 needs to use custom logic to allow data passing on gamethread.

Made the revert here: https://github.com/getnamo/UnrealEnginePython/commit/bc382d468a9d3123efdffb8695182c8276a6eb2f

**Pull request merged**
